trinfony_characters:
    resource: "@TrinfonyCharactersBundle/Controller/"
    type:     annotation
    prefix:   /

trinfony_auth:
    resource: "@TrinfonyAuthBundle/Controller/"
    type:     annotation
    prefix:   /
